name: Test

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: jsmvaldivia/file-splitter@0.1.0
      with:
        file-path: package-lock.json
        chunk-size: 10
    - run: |
        tree
